'on':
    - push
name: Create Release
jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: adopt
            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@v1
            - name: Build with Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: nightlyRelease
            - name: GitHub Release
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  prerelease: false
                  automatic_release_tag: 'bw.${{ github.run_number }}'
                  files: build/libs/*.jar
              
              # Deloy to the BlockWars server
            - name: Upload SFTP
              uses: genietim/ftp-action@releases/v4
              with:
                host: ${{ secrets.FTP_SERVER }}
                user: ${{ secrets.FTP_USERNAME }}
                password: ${{ secrets.FTP_PASSWORD }}
                localDir: "build/libs/Skript-blockwars.jar"
                remoteDir: "/plugins/"
            - name: Deploy Stage
              uses: fjogeleit/http-request-action@v1
              with:
                url: 'https://panel.ington.net/api/client/servers/${{ secrets.SERVER_ID }}/command'
                method: 'POST'
                bearerToken: ${{ secrets.PTERODACTYL_KEY }}
                customHeaders: '{"Content-Type": "application/json"}'
                data: '{"command":"dev:plugindeploy Skript"}'
